### ISSUE TITLE
Suggestions/Major(some more than others) feature requests

### ISSUE THREAD

**Issue by Servius** [Liam0102/Star-Wars-Vehicles#4]
Since we don't all have daily meetings/constantly talk to each other I felt it was a good idea to leave a list of what I consider some major features that should be added to the base system to make it easier on us when creating/updating our vehicles. 

Non-visual passenger seating that can be added to a vehicle's code with only a couple lines of code. Like 
```
          Ent.Seating = true
          Ent.SeatingMax = 8
```

The ability for the Pilot to eject his passengers via either /command or bound key enum. Should be able to disable this functionality with a couple one liners in the vehicles code. 
```
Ent.PassengerEject = true
Ent.EjectKey = [key](https://wiki.garrysmod.com/page/Enums/KEY)
```

[If you look at this link.](https://github.com/Servius/star-wars-vehicles-eu-pack/blob/master/star_wars_vehicles_eu_addon/lua/entities/bsp_bellator.lua) Youll see a pretty bland capital ship from my EU pack. Its a very simple vehicle meant to fly around and be used for server events. If you look through the code of a lot of the other vehicles in that repo a lot of them have repeated or even 1:1 repeated code. I believe we should look at cutting down on the amount of repeated code in vehicles and move more of it to the base. Like the previous two suggestions something like this: 
```lua
function ENT:StartLightSpeed()
	self.LightspeedPassengers = {};
	self.LightSpeed = true;
	self.LightSpeedTimer = CurTime() + 3;
	self.NextUse.LightSpeed = CurTime() + 20;
	local mb,mb2 = self:GetModelBounds();
	for k,v in pairs(ents.FindInBox(self:LocalToWorld(mb),self:LocalToWorld(mb2))) do
		if(v.IsSWVehicle and v!=self) then
		
			v.BeingWarped = true;
			v.ReturnToStandby = v.CanStandby;
			v.CanStandby = false;
			
			v:SetParent(self);
			
			self.LightspeedPassengers[k] = v;
		end
	end
end
```
Could be broken down to just: 
```
Ent.CanLightSpeed = true
Ent.LightSpeedDelay = "3" 
Ent.LightSpeedDistance = "20" 
```

Ive got some more but it might be worth setting up the project page instead that way we can all contribute our own desires/hopes/dreams/fantasies for alterations or feature additions to the base.

**Comment by Liam0102** [comment]
So what you're saying is, you what to do less work and want me to do more?

**Comment by Servius** [comment]
Im posting these to organize all of us. Im working, going to college, and trying to keep up with my own addons so its not like I have the time to implement every single dream feature I come up with and I'm sure the rest of you guys have similar cases of availability. 

Making it easier to add/remove functionality to a vehicle will not only save time for myself but it will also do the same for everyone working on their own vehicles as well. By adding new support to the base with a corresponding `Ent.CoolFunction = true` line we will also be able to have a more _clean_ looking template for the vehicles which should result in more unique and feature-plenty vehicles, more people interested in importing and creating new vehicles, and even allow us to potentially branch out from Star Wars vehicles to things like star trek, battlestar galactica, etc. (not saying I'm interested in branching out but making it easier to add a client side visual effect that looks like the enterprise entering warp speed would definitely help anyone that is)

**Comment by Servius** [comment]
I apologize if I came off as rude/crude in making the post. Was not my intention to nitpick or put out any bad vibes.

**Comment by Servius** [comment]
@Liam0102 Mind giving us perms to work on the project page?
