### ISSUE TITLE
Actual Bug; SW Vehicles Tab. 

### ISSUE THREAD

**Issue by Servius** [Liam0102/Star-Wars-Vehicles#5]
![alt text](http://image.prntscr.com/image/b9c34f11598c4fc29811149e20e40653.png "The problem")
While looking at moving my vehicles to the new tab I was clicking on stuff and found two issues. 

1. Right clicking an entity in the menu does not display the entire usual list of options like ["spawn using toolgun"](http://image.prntscr.com/image/c8b9eca4f29b4ffc84508d8244b23da1.png)
2. [Can't spawn the weapons for some reason.](http://image.prntscr.com/image/14692fb7e5de4568a2fcd38edd128d40.png) 

Love the look of the new tab. Sorry for the second issue post but this is completely separate from the other thing and I wasn't aware of the problem until only a couple minutes ago(way after the first issue post was created).

**Comment by Liam0102** [comment]
I'm aware of this, and have mostly fixed (Just haven't updated GIT)
