### ISSUE TITLE
Network usage. 

### ISSUE THREAD

**Issue by Servius** [Liam0102/Star-Wars-Vehicles#8]
http://steamcommunity.com/sharedfiles/filedetails/?id=622814666
^ Found this addon and I believe it could help with the following issue: Server physics breaking mid vehicle combat seems to a pretty common issue for mid-low end servers or poorly optimized large servers.

**Comment by Liam0102** [comment]
From what I believe the problem was caused by a ShouldCollide hook in the torpedo code and has since been fixed(No one has complained since)

**Comment by Servius** [comment]
Alright. Happy to hear physics breaking is no longer an issue. Would implementing this here still help with overall performance though?

**Comment by Servius** [comment]
``` lua
local Category = "Syphadias"

local function StandAnimation( vehicle, player )
	return player:SelectWeightedSequence( ACT_HL2MP_IDLE_PASSIVE ) 
end

local V = {
	Name = "Syphas Custom Seat",
	Model = "models/nova/airboat_seat.mdl",
	Class = "prop_vehicle_prisoner_pod",
	Category = Category,

	Author = "Syphadias",
	Information = "Seat by Syphadias with custom animation",
	Offset = 5,

	KeyValues = {
		vehiclescript = "scripts/vehicles/prisoner_pod.txt",
		limitview = "0"
	},
	Members = {
		HandleAnimation = StandAnimation,
	}
}
list.Set( "Vehicles", "sypha_seat", V )

```

**Comment by Liam0102** [comment]
According to the GIT notes on the issue with pods, the increase in performance is negligible and causes issues with the pods themselves: https://github.com/Facepunch/garrysmod-issues/issues/2452

(Last comment)

**Comment by Servius** [comment]
Interesting. It may be worth just verifying the effects mentioned there. Not that I don't believe Rubat but I just don't know if Rubat has a live testing multiplayer environment to be able to check for network stability changes. On the addon description it says it will only have a noticeable effect in multiplayer and really only when there are a large quantity of seats. 

We could probably contact one of the large pop servers and ask them to do something with a few LAATs. Once without the addon and another with.
